### ISSUE TITLE
Nix remote builds socket error

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#3556]
We often see `error: cannot connect to socket at '/nix/var/nix/gc-socket/socket': No such file or directory` when running builds. It's unclear why this happens but it kills CI jobs and they have to be manually restarted.

e.g. https://github.com/holochain/holochain/actions/runs/8569586697/job/23485809644?pr=3544#step:4:380

**Comment by steveej** [comment]
there's a good chance this is fixed in [nix >=2.20.0](https://github.com/NixOS/nixpkgs/issues/72372).

**Comment by steveej** [comment]
@ThetaSinner have you seen this issue recently? `linux-builder-01` has been on nix 2.20 for a few weeks.

**Comment by ThetaSinner** [comment]
Yep still seeing it -> https://github.com/holochain/holochain/actions/runs/9029823024/job/24812917741?pr=3845

**Comment by steveej** [comment]
> have you seen this issue recently? `linux-builder-01` has been on nix 2.20 for a few weeks.

i was misremembering this. the nix version in the holochain-infra repo [is still on 2.18.1](https://github.com/holochain/holochain-infra/blob/3795e42e70a8b431e8f95145b68f514ae1af5ad1/modules/nixos/shared.nix#L19). which is actually good news, so there's a chance to fix this with the next update.

**Comment by ThetaSinner** [comment]
https://github.com/holochain/holochain/actions/runs/9111824657/job/25049787186?pr=3857
